export const vansArr = [
  {
    id: 0,
    title: "Bulldawg",
    capacity: 8,
    image: require("./images/mat1.jpeg"),
    rate: 4,
    booked: true,
    price: 12000.0,
  },
  {
    id: 1,
    title: "Topdawg",
    capacity: 9,
    image: require("./images/mat2.jpg"),
    rate: 4,
    booked: false,
    price: 12000.0,
  },
  {
    id: 2,
    title: "Wardawg",
    capacity: 14,
    image: require("./images/mat3.jpg"),
    rate: 3,
    booked: false,
    price: 15000.0,
  },
  {
    id: 3,
    title: "Politedawg",
    capacity: 8,
    image: require("./images/mat4.jpg"),
    rate: 5,
    booked: true,
    price: 12000.0,
  },
  {
    id: 4,
    title: "Killerdawg",
    capacity: 14,
    image: require("./images/mat5.png"),
    rate: 4,
    booked: false,
    price: 17000.0,
  },
  {
    id: 5,
    title: "Cleandawg",
    capacity: 4,
    image: require("./images/mat6.jpg"),
    rate: 4,
    booked: true,
    price: 9000.0,
  },
  {
    id: 6,
    title: "Bigdawg",
    capacity: 8,
    image: require("./images/mat7.jpeg"),
    rate: 5,
    booked: false,
    price: 12000.0,
  },
  {
    id: 7,
    title: "Talldawg",
    capacity: 12,
    image: require("./images/mat8.jpg"),
    rate: 3,
    price: 13000.0,
  },
  {
    id: 8,
    title: "Gyalisdawg",
    capacity: 8,
    image: require("./images/mat9.png"),
    rate: 4,
    booked: false,
    price: 12000.0,
  },
  {
    id: 9,
    title: "Shydawg",
    capacity: 4,
    image: require("./images/mat10.jpg"),
    rate: 5,
    booked: false,
    price: 15000.0,
  },
];
